Repository cse110-fa21-group16/cse110-fa21-group16, pull requests merged in 2021-11, with the labels that each got.

#25 Edit page UI - Resolves #14
  source/.gitignore
  source/assets/components/EditRecipe.js
  source/assets/styles/main.css
Labels: front-end

#38 Fetch data - landing page - Solved #36
  source/assets/components/RecipeCardFea.js
  source/assets/components/RecipeCardMy.js
  source/assets/scripts/main.js
  source/assets/styles/main.css
  source/index.html
Labels: back-end

#53 Added cicd markdown documentation
  admin/cipipeline/phase1.md
Labels: documentation, pipeline

#68 Remove steps
  source/assets/components/AddRecipe.js
  source/assets/components/EditRecipe.js
Labels: bug, enhancement, back-end

#80 Remove Extra Plus Sign in Bottom Right of Screen
  source/index.html
Labels: front-end, clean-up

#82 Remove placeholder text for add/edit recipes
  source/assets/components/AddRecipe.js
  source/assets/components/EditRecipe.js
Labels: front-end, clean-up

#67 Implemented spam prevention + Fixed deploy preview cors error
  package-lock.json
  package.json
  source/.netlify/functions/fetch-data.js
  source/assets/scripts/main.js
Labels: back-end, API

#85 Finished initial routing and modularized entire main.js AND nutrition view page
  source/.netlify/functions/fetch-data.js
  source/assets/components/AddRecipe.js
  source/assets/components/EditRecipe.js
  source/assets/components/NewCard.js
  source/assets/components/NewCardMyPage.js
  source/assets/components/NutritionPage.js
  source/assets/components/RecipeCardFea.js
  source/assets/components/RecipeCardFeaturedPG.js
  source/assets/components/RecipeCardMy.js
  source/assets/components/RecipeCardMyMyPage.js
  source/assets/components/ViewFeaRecipe.js
  source/assets/components/ViewMyRecipe.js
  source/assets/components/deleteConfirmation.js
  source/assets/scripts/Router.js
  source/assets/scripts/helpCrudFunc.js
  source/assets/scripts/helpGetDataFunc.js
  source/assets/scripts/main.js
  source/index.html
Labels: back-end

#87 Fixed nutrition/edit/add page bugs and int/string bug for ingredients
  source/assets/scripts/helpGetDataFunc.js
  source/assets/scripts/main.js
Labels: bug

#91 Resolved #90 - [BUG] Can't submit edited recipe without image
  source/assets/components/AddRecipe.js
Labels: bug

#92 Add Zest logo and name
  source/assets/components/AddRecipe.js
  source/assets/components/EditRecipe.js
  source/assets/components/ViewFeaRecipe.js
  source/assets/components/ViewMyRecipe.js
  source/assets/images/icons/zest-ico.png
  source/assets/images/icons/zest.ico
  source/assets/images/icons/zest.png
  source/assets/images/logo-temp-2.PNG
  source/assets/images/logo-temp-3.png
  source/assets/images/logo-temp.png
  source/assets/styles/main.css
  source/index.html
  specs/adrs/111421-LogoName.md
Labels: enhancement, front-end

#95 Changed logo size to fixed px
  source/assets/components/AddRecipe.js
  source/assets/components/EditRecipe.js
  source/assets/styles/main.css
Labels: bug, enhancement, front-end

#102 Fixed recipes' instructions formatting. Fixed add button landing page
  source/assets/components/NewCard.js
  source/assets/components/ViewFeaRecipe.js
  source/assets/scripts/helpGetDataFunc.js
Labels: bug, back-end

#117 Added documentation for all components and refactored object-oriented design
  source/assets/components/AddRecipe.js
  source/assets/components/EditRecipe.js
  source/assets/components/EmptyCard.js
  source/assets/components/NewCard.js
  source/assets/components/NewCardMyPage.js
  source/assets/components/NutritionPage.js
  source/assets/components/RecipeCardFea.js
  source/assets/components/RecipeCardFeaturedPG.js
  source/assets/components/RecipeCardMy.js
  source/assets/components/RecipeCardMyMyPage.js
  source/assets/components/ViewFeaRecipe.js
  source/assets/components/ViewMyRecipe.js
  source/assets/components/deleteConfirmation.js
  source/assets/scripts/Router.js
  source/assets/scripts/helpCrudFunc.js
  source/assets/scripts/helpGetDataFunc.js
  source/assets/scripts/main.js
Labels: documentation, back-end

#118 Minor documentation
  source/assets/scripts/main.js
Labels: documentation

#123 Testing code coverage workflow
  .github/workflows/test.yml
  __test__/ui.test.js
  package.json
Labels: testing

#120 Added 4 filtering for diet restrictions
  source/assets/scripts/main.js
  source/assets/styles/main.css
  source/index.html
Labels: enhancement, front-end, back-end

#125 Removed filter button
  source/index.html
Labels: clean-up

#126 Unit conversion
  source/.netlify/functions/convert-unit.js
  source/assets/components/ViewFeaRecipe.js
  source/assets/components/ViewMyRecipe.js
  source/assets/scripts/helpGetDataFunc.js
  source/assets/scripts/main.js
Labels: enhancement, front-end, back-end

#137 *Fixed* Nutrition facts calculations won't accept negative values
  source/assets/components/NutritionPage.js
Labels: bug, back-end

#128 Add TTS to My Recipes and Featured/Favorites Recipe Pages
  source/assets/components/ViewFeaRecipe.js
  source/assets/components/ViewMyRecipe.js
Labels: enhancement, front-end, back-end
