Repository cse110-fa21-group16/cse110-fa21-group16, pull requests merged in 2021-12, with the labels that each got.

#127 Puppeteer add recipe
  __test__/addRecipe.test.js
  __test__/ui.test.js
  jest-puppeteer.config.js
Labels: back-end, testing

#144 Cancel tts on feature to other pages and added check for empty steps/ingredients
  source/assets/components/AddRecipe.js
  source/assets/components/EditRecipe.js
  source/assets/components/RecipeCardFea.js
  source/assets/components/RecipeCardFeaturedPG.js
  source/assets/components/RecipeCardMy.js
  source/assets/components/RecipeCardMyMyPage.js
  source/assets/components/ViewFeaRecipe.js
  source/assets/components/ViewMyRecipe.js
  source/assets/scripts/main.js
Labels: bug, enhancement

#154 Puppeteer test for feature and favorite page
  __test__/addRecipe.test.js
  __test__/feaFav.test.js
Labels: testing

#152 Unit tests for helpGetDataFunc.js
  __test__/helpGetDataFunc.test.js
  babel.config.json
  package-lock.json
  package.json
  source/assets/components/NutritionPage.js
  source/assets/scripts/helpCrudFunc.js
  source/assets/scripts/helpGetDataFunc.js
Labels: testing

#158 Unit testing for helpCrudFunc.js
  __test__/helpCrudFunc.test.js
  __test__/helpGetDataFunc.test.js
  source/assets/components/AddRecipe.js
  source/assets/components/EditRecipe.js
  source/assets/components/RecipeCardFeaturedPG.js
  source/assets/components/ViewFeaRecipe.js
  source/assets/components/deleteConfirmation.js
  source/assets/scripts/helpCrudFunc.js
Labels: testing

#161 [EMERGENCY ]Fixed crud function parameters for mobile views
  __test__/addRecipe.test.js
  __test__/feaFav.test.js
  screenshot3.png
  source/assets/components/AddRecipeMobile.js
  source/assets/components/EditRecipeMobile.js
  source/assets/components/ViewFeaRecipeMobile.js
Labels: bug, back-end
